set(SFSE_VERSION_MAJOR 0)
set(SFSE_VERSION_MINOR 2)
set(SFSE_VERSION_PATCH 3)

set(RUNTIME_VERSION_MAJOR 1)
set(RUNTIME_VERSION_MINOR 9)
set(RUNTIME_VERSION_PATCH 67)
set(RUNTIME_VERSION_TYPE 0)

math(
	EXPR
	RUNTIME_VERSION_PACKED
	"((${RUNTIME_VERSION_MAJOR} & 0xFF) << 24) | ((${RUNTIME_VERSION_MINOR} & 0xFF) << 16) | ((${RUNTIME_VERSION_PATCH} & 0xFFF) << 4) | (${RUNTIME_VERSION_TYPE} & 0xF)"
	OUTPUT_FORMAT
		HEXADECIMAL
)
