set(SFSE_VERSION_MAJOR 0)
set(SFSE_VERSION_MINOR 1)
set(SFSE_VERSION_PATCH 0)

set(RUNTIME_VERSION_MAJOR 1)
set(RUNTIME_VERSION_MINOR 7)
set(RUNTIME_VERSION_PATCH 23)
set(RUNTIME_VERSION_TYPE 0)

math(
	EXPR
	RUNTIME_VERSION_PACKED
	"((${RUNTIME_VERSION_MAJOR} & 0xFF) << 24) | ((${RUNTIME_VERSION_MINOR} & 0xFF) << 16) | ((${RUNTIME_VERSION_PATCH} & 0xFFF) << 4) | (${RUNTIME_VERSION_TYPE} & 0xF)"
	OUTPUT_FORMAT
		HEXADECIMAL
)
